### ISSUE TITLE
UnboundLocalError: local variable 'val' referenced before assignment

### ISSUE THREAD

**Issue by rrauenza** [dvershinin/sde#4]
-s doesn't work.   

val is only defined if -s is not true:

  if not args.is_string:
        val = normalize_val(args.val)
        
        

```
(virtualenv-3.6.8) <perfdash-web1:/opt/perfdash/perfdash.git/bin>$ sde -s logs foo foo.yaml
Traceback (most recent call last):
  File "/opt/perfdash/perfdash.git/virtualenv-3.6.8/bin/sde", line 8, in <module>
    sys.exit(main())
  File "/opt/perfdash/perfdash.git/virtualenv-3.6.8/lib64/python3.6/site-packages/sde/sde.py", line 114, in main
    edit_file(args.key, val, args.file, fmt, must_exist=args.must_exist)
UnboundLocalError: local variable 'val' referenced before assignment
```

**Comment by rrauenza** [comment]
https://github.com/dvershinin/sde/pull/5

**Comment by dvershinin** [comment]
Thank you very much.
